spring:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: Lax
  config:
    import: optional:file:.env[.properties]
  application:
    name: schedule_manager
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: BINARY
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
jwt:
  secret:
    key: ${JWT_SECRET_KEY}